# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: ./
author_email: 45483159+twsl@users.noreply.github.com
author_username: twsl
copyright_holder: twsl
copyright_holder_email: 45483159+twsl@users.noreply.github.com
copyright_license: MIT
copyright_year: 2024
custom_install: true
github_runner:
- ubuntu-latest
github_runner_python_version:
- '3.11'
include_copilot: false
include_databricks: false
include_docs: true
include_notebooks: true
include_sample_code: false
line_ending: lf
primary_branch: main
project_description: 'The python description'
project_name: example-project
python_package_command_line_name: example-project
python_package_distribution_name: example-project
python_package_import_name: example_project
python_version: '3.11'
repository_name: example-project
repository_namespace: twsl
repository_provider: github.com
self_signed: false
use_precommit: true
copier_auto_update: true
