# See here for image contents: https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/Dockerfile
# See here for proposed version of container: https://github.com/devcontainers/templates/blob/main/src/python/devcontainer-template.json

# [Choice] Python version (use -bookworm or -bullseye variants on local arm64/Apple Silicon): 3, 3.13, 3.12, 3.11, 3.10, 3.9, 3-bookworm, 3.13-bookworm, 3.12-bookworm, 3.11-bookworm, 3.10-bookworm, 3.9-bookworm, 3-bullseye, 3.13-bullseye, 3.12-bullseye, 3.11-bullseye, 3.10-bullseye, 3.9-bullseye, 3-buster, 3.12-buster, 3.11-buster, 3.10-buster, 3.9-buster
ARG VARIANT=3-trixie
FROM mcr.microsoft.com/devcontainers/python:3-${VARIANT}

RUN pip install --upgrade pip{% if package_manager == 'poetry' %}

# Install poetry
ENV PATH="/etc/poetry/bin:$PATH"
RUN curl -sSL {% if self_signed %}-k{% endif %} https://install.python-poetry.org | POETRY_HOME=/etc/poetry python - \
    && poetry completions bash >> ~/.bash_completion \
    && poetry config virtualenvs.create false \
    && poetry self add "poetry-dynamic-versioning[plugin]"{% elif package_manager == 'uv'%}

# Install uv
ENV PATH="/root/.local/bin/:$PATH"
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN echo 'eval "$(uv generate-shell-completion bash)"' >> ~/.bashrc \
    && echo 'eval "$(uvx --generate-shell-completion bash)"' >> ~/.bashrc{% endif %}

{% if self_signed %}RUN echo "--insecure" > ~/.curlrc{% endif %}
